FROM python:3.9-slim

# Directorio de trabajo
WORKDIR /app

# Instalamos dependencias del sistema necesarias (si las hubiera)
RUN apt-get update && apt-get install -y default-libmysqlclient-dev build-essential

# Copiamos el archivo de requerimientos e instalamos las librerías de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos todo el código (scripts y entrypoint)
COPY . .

# Damos permisos de ejecución al script de entrada
RUN chmod +x entrypoint.sh

# Definimos el entrypoint para controlar qué nivel se ejecuta
ENTRYPOINT ["./entrypoint.sh"]